version: '3'
services:
  mongodb:
    image: mongo:4.0-xenial
    restart: always
#    volumes:
#    - mongodb_data:/data/db
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: taobao
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
#volumes:
#  mongodb_data:
#    driver: local
